### PR TITLE
I1 station index do

### PR DESCRIPTION
**Pull request by blackknight75**
Fixed rspec by rebuilding/migrating db. Styling works for index/new/delete/show page.

### CODE REVIEW

**Comment by meyerhoferc** [comment]
I'm so excited to see what this looks this! Awesome work, Dan.

**Comment by TheKaterTot** [comment]
This is going to be awesome!

**Comment by blackknight75** [comment]
https://www.google.com/search?q=skeptical+cat+meme&espv=2&biw=1440&bih=759&tbm=isch&imgil=44EV4xRB4iABAM%253A%253BOTxfMM1_DjKkQM%253Bhttps%25253A%25252F%25252Fwww.pinterest.com%25252Fpin%25252F145452262942235463%25252F&source=iu&pf=m&fir=44EV4xRB4iABAM%253A%252COTxfMM1_DjKkQM%252C_&usg=__5yCb7geQcSy6vzvnLpyRHFi5d8A%3D&ved=0ahUKEwiy54zllebRAhVqrlQKHYRgDHkQyjcIJQ&ei=-ECNWLKLLOrc0gKEwbHIBw#imgrc=44EV4xRB4iABAM%3A

**Comment by blackknight75** [comment]
https://s-media-cache-ak0.pinimg.com/736x/18/20/2b/18202b5e1bcf07367849ca9b4f81b2df.jpg

**Pull request merged**
